sudo: required

services:
  - docker

install:
  - sudo apt-get -y install jq

language: bash

script:
  - docker_versions=`curl -sSL 'https://registry.hub.docker.com/v2/repositories/bubuntux/riot-web/tags?page_size=1024' | jq '."results"[]["name"]' | tr -d '"' | sort --version-sort`
  - echo $docker_versions
#  - ./main.sh