name: build-docker

on:
  release:
    types: 
      - published
      - created
  
  workflow_dispatch:
    inputs:
      version:
        description: 'Test scenario version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4

      - name: set up qemu
        uses: docker/setup-qemu-action@v1.2.0

      - name: set up buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          buildkitd-flags: --debug
          
      - name: login to docker hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          
      # - name: login to github container registry
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GH_REGISTRY_USERNAME }}
      #     password: ${{ secrets.GH_REGISTRY_TOKEN }}
      
      - name: get tag name
        id: tag_name
        run: |
          [ -z "${{ github.event.inputs.version }}" ] && echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/} || echo ::set-output name=SOURCE_TAG::${{ github.event.inputs.version }}  
                
      - name: build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          build-args: version=${{ steps.tag_name.outputs.SOURCE_TAG }}
          tags: |
            dotwee/element-web-multiarch:${{ steps.tag_name.outputs.SOURCE_TAG }}
            dotwee/element-web-multiarch:latest
          #  ghcr.io/dotwee/element-web-multiarch:${{ steps.tag_name.outputs.SOURCE_TAG }}
          #  ghcr.io/dotwee/element-web-multiarch:latest
